services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://postgres:admin@localhost:5432/elite_patient
      - HOSTNAME=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped