services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      # Override DATABASE_URL to use host.docker.internal which points to the host machine
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/elite_patient
    env_file:
      - .env
    restart: unless-stopped
    # Add extra_hosts to make host.docker.internal work on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
