services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "3002:3002"  # This is ignored but kept for docs
    environment:
      - DATABASE_URL=postgres://postgres:admin@localhost:5432/elite_patient
      - NEXT_PUBLIC_APP_URL=https://patient-elite.elitemedicaleservices.tn
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
